language: node_js
node_js:
  - '8'
  - '10'
install:
  - npm install -g codecov
script:
  - yarn install
  - yarn lint
  - yarn test:coverage --runInBand --no-cache
  - yarn test --runInBand --no-cache
  - codecov
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
